import { Button, Paper, TextField } from '@mui/material';
import React, { useState } from 'react';

interface NextPromptFormProps  {
    submit: (prompt: string) => void,
    imageUrl: string
};

const NextPromptForm: React.FC<NextPromptFormProps> = ({submit, imageUrl}) => {
    const [prompt, setPrompt] = useState('');

    const onClick = (e: any) => {
        submit(prompt);
    };

    const onPromptInput = (e: any) => {setPrompt(e.target.value)};

    return (
        <div>
            <Paper variant="outlined">
                <img src={imageUrl}
                alt="generated by ai" />
            </Paper>
            <TextField label='What prompt generated this image?'
                value={prompt}
                onInput={onPromptInput}
            />
            <Button onClick={onClick}>Submit</Button>
        </div>
    );
};

export default NextPromptForm;